/** Auto-generated from docs/knowledge/vanessa/GRAFICOS MESA.txt — V2.6b parity */

export interface Mesa35GraphKnowledgeRow {
  title: string;
  therapistExplanation: string;
  clientExplanation: string;
  activationText: string;
}

export const MESA35_GRAPH_KNOWLEDGE: Record<string, Mesa35GraphKnowledgeRow> = {
  "anti-possessao": { title: "Anti Possessão", therapistExplanation: "Gráfico radiestésico de proteção espiritual profunda, utilizado para remover obsessores, entidades e energias negativas invasoras.", clientExplanation: "Informe ao cliente que será realizada uma limpeza energética para remover influências externas negativas, restaurando o livre-\narbítrio espiritual.", activationText: "Ativo agora Anti Possessão, limpando profundamente todas as energias obsessivas, entidades e vínculos espirituais negativos do passado, presente e futuro que estejam \ninfluenciando (nome do consulente). Que seja imediatamente restaurada a soberania espiritual, a proteção e a luz divina. Assim é, está feito, gratidão." },
  "triturador": { title: "Triturador", therapistExplanation: "Gráfico que atua na quebra de padrões negativos, formas-pensamento e crenças limitantes.", clientExplanation: "Será feita uma liberação de padrões mentais e emocionais repetitivos que estejam limitando sua vida ou causando bloqueios.", activationText: "Ativo agora Triturador, dissolvendo profundamente todas as formas-pensamento negativas, crenças limitantes e padrões repetitivos do passado, presente e futuro que \nestejam impedindo o avanço de (nome do consulente). Que se estabeleça liberdade mental e emocional. \nAssim é, está feito, gratidão." },
  "yoshua": { title: "Yoshua", therapistExplanation: "Gráfico radiestésico de cura profunda, conexão espiritual elevada e equilíbrio emocional.", clientExplanation: "Informe ao cliente que será ativada uma energia poderosa para cura profunda, equilíbrio emocional e conexão espiritual.", activationText: "Ativo agora Yoshua, limpando profundamente todas as energias negativas e bloqueios do passado, presente e futuro que possam estar impedindo a cura profunda, o equilíbrio emocional e a conexão espiritual elevada em (nome do consulente). Que seja imediatamente estabelecida paz interior, cura total e centramento espiritual profundo. Assim é, está feito, gratidão." },
  "luxor": { title: "Luxor", therapistExplanation: "Gráfico de alinhamento espiritual, conexão com sabedoria ancestral e reequilíbrio energético profundo.", clientExplanation: "Será ativada uma energia de sabedoria ancestral que promoverá equilíbrio espiritual e reconexão com o seu centro de poder interior.", activationText: "Ativo agora Luxor, limpando todos os desequilíbrios espirituais, bloqueios e distorções do passado, presente e futuro em (nome do consulente). Que se estabeleça o alinhamento com a sabedoria ancestral e a força do espírito. Assim é, está feito, gratidão." },
  "quadrata": { title: "Quadrata", therapistExplanation: "Gráfico de estrutura, foco e organização do campo mental e energético.", clientExplanation: "Ativaremos uma energia de clareza e organização para trazer mais foco, estabilidade e estrutura interior.", activationText: "Ativo agora Quadrata, limpando toda desorganização energética, confusão mental e falta de foco do passado, presente e futuro em (nome do consulente). Que se estabeleça organização interior, estabilidade e clareza. Assim é, está feito, gratidão." },
  "anti-depressao": { title: "Anti Depressão", therapistExplanation: "Gráfico que atua elevando a vibração, dissolvendo estados de tristeza profunda e restaurando o prazer de viver.", clientExplanation: "Será feita uma harmonização emocional para reduzir sintomas de tristeza, resgatar a alegria e o entusiasmo pela vida.", activationText: "Ativo agora Anti Depressão, limpando todas as memórias e energias de tristeza, desânimo e vazio existencial do passado, presente e futuro em (nome do consulente). Que a alegria de viver, o entusiasmo e a força vital sejam restaurados. Assim é, está feito, gratidão." },
  "magnetismo-curativo": { title: "Magnetismo Curativo", therapistExplanation: "Gráfico que ativa o campo de magnetismo para atrair e irradiar energia de cura.", clientExplanation: "Será ativado o magnetismo natural do seu corpo para acelerar o processo de cura física, emocional e espiritual.", activationText: "Ativo agora Magnetismo Curativo, ativando o campo de cura e regeneração em todos os níveis no campo de (nome do consulente). Que a energia curativa flua e restaure plenamente o equilíbrio do passado, presente e futuro. Assim é, está feito, gratidão." },
  "turbilhao-jupiter": { title: "Turbilhão Júpiter", therapistExplanation: "Gráfico de expansão, prosperidade e crescimento energético.", clientExplanation: "Será ativada uma energia de abertura de caminhos, expansão da sua força de ação e prosperidade.", activationText: "Ativo agora Turbilhão Júpiter, limpando bloqueios de expansão, travas financeiras e limitações do passado, presente e futuro em (nome do consulente). Que se manifeste a prosperidade, o crescimento e a abundância. Assim é, está feito, gratidão." },
  "saude-financeira": { title: "Saúde Financeira", therapistExplanation: "Gráfico que limpa bloqueios relacionados ao dinheiro e ativa o fluxo de prosperidade e equilíbrio financeiro.", clientExplanation: "Vamos harmonizar sua energia com o dinheiro, ativando equilíbrio e abrindo caminhos para a abundância material.", activationText: "Ativo agora Saúde Financeira, limpando todas as crenças limitantes, traumas e escassez do passado, presente e futuro que impedem o fluxo de prosperidade em (nome do consulente). Que se estabeleça equilíbrio e liberdade financeira. Assim é, está feito, gratidão." },
  "piramide-plana-om": { title: "Pirâmide Plana com OM", therapistExplanation: "Gráfico de elevação vibracional, alinhamento espiritual e harmonização profunda através da geometria sagrada e do som primordial.", clientExplanation: "Será ativada uma energia de purificação espiritual e elevação vibracional, para restaurar seu alinhamento com o divino.", activationText: "Ativo agora Pirâmide Plana com OM, limpando desequilíbrios energéticos e espirituais do passado, presente e futuro em (nome do consulente). Que a frequência divina do OM traga paz, equilíbrio e reconexão com o Eu Superior. Assim é, está feito, gratidão." },
  "dissipador": { title: "Dissipador", therapistExplanation: "Gráfico usado para dissipar energias densas, pensamentos obsessivos e cargas emocionais estagnadas.", clientExplanation: "Será realizada uma limpeza profunda para dissolver toda densidade emocional e mental acumulada.", activationText: "Ativo agora Dissipador, dissolvendo todas as cargas emocionais, pensamentos negativos e energias densas do campo de (nome do consulente). Que a leveza, o equilíbrio \ne a clareza se estabeleçam. Assim é, está feito, gratidão." },
  "desimpregnador": { title: "Desimpregnador", therapistExplanation: "Gráfico que remove cargas, miasmas e energias impregnadas no campo áurico e emocional.", clientExplanation: "Será feita uma desimpregnação energética completa para restaurar sua leveza e clareza vibracional.", activationText: "Ativo agora Desimpregnador, removendo todas as energias impregnadas, miasmas e cargas emocionais no campo de (nome do consulente). Que a leveza, a clareza e a vitalidade se restabeleçam. Assim é, está feito, gratidão." },
  "justica-divina": { title: "Justiça Divina", therapistExplanation: "Gráfico de equilíbrio kármico, liberação de injustiças e reconexão com a ordem divina.", clientExplanation: "Vamos ativar a frequência da Justiça Divina para alinhar sua vida com a verdade espiritual e restaurar o senso de justiça.", activationText: "Ativo agora Justiça Divina, limpando todos os registros de injustiça, abusos e desequilíbrios do passado, presente e futuro em (nome do consulente). Que a verdade, o equilíbrio e o merecimento se manifestem. Assim é, está feito, gratidão." },
  "sol-da-vida": { title: "Sol da Vida", therapistExplanation: "Gráfico que ativa o brilho pessoal, a vitalidade, a força interior e a alegria de viver.", clientExplanation: "Vamos restaurar sua energia vital, \nfortalecer sua presença e despertar a alegria genuína de viver.", activationText: "Ativo agora Sol da Vida, despertando a vitalidade, a alegria e o brilho interior em (nome do consulente), limpando padrões de apatia e desânimo do passado, presente e futuro. Que a força da vida volte a pulsar com entusiasmo. Assim é, está feito, gratidão." },
  "energizador": { title: "Energizador", therapistExplanation: "Gráfico que fortalece o campo energético, repondo energia vital e restaurando a disposição física e espiritual.", clientExplanation: "Será feita uma recarga energética para restaurar sua força, foco e vitalidade.", activationText: "Ativo agora Energizador, recarregando o campo vital de (nome do consulente), restaurando sua força, energia e motivação. Que toda exaustão do passado, presente e \nfuturo seja transmutada. Assim é, está feito, gratidão." },
  "anti-dor": { title: "Anti Dor", therapistExplanation: "Gráfico que alivia dores físicas e emocionais, promovendo conforto e regeneração energética.", clientExplanation: "Vamos suavizar dores do corpo e da alma, promovendo alívio e conforto imediato.", activationText: "Ativo agora Anti Dor, aliviando as dores físicas e emocionais em (nome do consulente), limpando os registros de sofrimento e desconforto do passado, presente e futuro. Que a cura e o conforto se instalem com leveza. Assim é, está feito, gratidão." },
  "anti-magia": { title: "Anti Magia", therapistExplanation: "Gráfico de proteção espiritual que neutraliza magias, inveja, feitiços e ataques energéticos.", clientExplanation: "Vamos realizar uma proteção energética profunda contra qualquer forma de energia nociva, intencional ou não.", activationText: "Ativo agora Anti Magia, neutralizando toda e qualquer magia negativa, inveja, ataques espirituais e manipulações no campo de (nome do consulente). Que a proteção divina se fortaleça. Assim é, está feito, gratidão." },
  "iave-sete-circulos": { title: "Iavé – Sete Círculos", therapistExplanation: "Gráfico de conexão com o Sagrado, que traz proteção, luz e orientação espiritual elevada.", clientExplanation: "Vamos abrir um campo de luz com elevada proteção e alinhamento com o plano divino.", activationText: "Ativo agora Iavé – Sete Círculos, conectando (nome do consulente) com a energia divina da Fonte Criadora, limpando interferências espirituais e trazendo luz, proteção e orientação do passado, presente e futuro. Assim é, está feito, gratidão." },
  "mesa-damien": { title: "Mesa Damien", therapistExplanation: "Gráfico multifuncional de reequilíbrio energético, usado para alinhamento espiritual, limpeza profunda e ativação de forças internas.", clientExplanation: "Será ativada uma mesa completa que trabalha vários aspectos do seu campo ao mesmo tempo: limpeza, cura e alinhamento.", activationText: "Ativo agora Mesa Damien, promovendo uma limpeza multidimensional e alinhamento completo no campo de (nome do consulente), restaurando equilíbrio, proteção e clareza \nespiritual do passado, presente e futuro. Assim é, está feito, gratidão." },
  "heptapentagrama": { title: "Heptapentagrama", therapistExplanation: "Gráfico de proteção espiritual para os sete corpos sutis. Atua blindando o campo contra qualquer tipo de ataque energético.", clientExplanation: "Será criado um escudo espiritual para proteger todo o seu campo energético de energias externas.", activationText: "Ativo agora Heptapentagrama, blindando os sete corpos sutis de (nome do consulente) contra-ataques espirituais, interferências e energias invasoras do passado, presente e futuro. Que a proteção divina se estabeleça. Assim é, está feito, gratidão." },
  "revitalizador-chakras": { title: "Revitalizador de Chakras", therapistExplanation: "Gráfico de ativação e equilíbrio dos chakras. Reenergiza os centros vitais e restaura o fluxo energético.", clientExplanation: "Vamos ativar e harmonizar todos os seus chakras, promovendo equilíbrio e bem-estar.", activationText: "Ativo agora Revitalizador de Chakras, equilibrando e reenergizando todos os centros de energia de (nome do consulente), limpando bloqueios e promovendo o fluxo saudável do passado, presente e futuro. Assim é, está feito, gratidão." },
  "scap-cabalista": { title: "Scap Cabalístico", therapistExplanation: "Gráfico de limpeza e energização simultânea. Libera impurezas e fortalece o campo sutil.", clientExplanation: "Será feita uma limpeza intensa e imediata do campo, ao mesmo tempo em que será energizado com luz vital.", activationText: "Ativo agora Scap, limpando profundamente e energizando o campo de (nome do consulente), removendo impurezas, densidades e restaurando o brilho da aura do passado, presente e futuro. Assim é, está feito, gratidão." },
  "quadrado-magico": { title: "Quadrado Mágico", therapistExplanation: "Gráfico de ordenação mental e emocional. Promove clareza de pensamento, foco e organização interior.", clientExplanation: "Será organizada a energia mental e emocional para trazer mais foco, ordem interna e segurança.", activationText: "Ativo agora Quadrado Mágico, organizando o campo mental e emocional de (nome do consulente), limpando a confusão, desordem e instabilidade do passado, presente e futuro. Que a clareza e o foco se instalem com sabedoria. Assim é, está feito, gratidão." },
  "sorte-sucesso": { title: "Sorte e Sucesso", therapistExplanation: "Gráfico que atrai oportunidades, ativa o magnetismo da sorte e abre caminhos para o sucesso.", clientExplanation: "Será realizada uma ativação para aumentar seu magnetismo e atrair oportunidades e prosperidade.", activationText: "Ativo agora Sorte e Sucesso, ativando o magnetismo da prosperidade no campo de (nome do consulente), limpando bloqueios que impedem o sucesso do passado, presente e \nfuturo. Que as oportunidades fluam com leveza. Assim é, está feito, gratidão." },
  "cubo-metatron": { title: "Cubo de Metatron", therapistExplanation: "Gráfico de geometria sagrada usado para proteção, cura multidimensional e alinhamento com a luz divina.", clientExplanation: "Será ativada a geometria sagrada de proteção e realinhamento com a energia divina de Metatron.", activationText: "Ativo agora Cubo de Metatron, alinhando o campo energético de (nome do consulente) com a luz divina, limpando interferências multidimensionais do passado, presente e futuro. Que a proteção sagrada e a cura superior se instalem. Assim é, está feito, gratidão." },
  "desembaracador-relacionamentos": { title: "Desembaraçador de Relacionamentos", therapistExplanation: "Gráfico que atua na liberação de vínculos tóxicos, dependência emocional e padrões negativos em relações afetivas.", clientExplanation: "Vamos trabalhar os laços energéticos nocivos para limpar padrões repetitivos e promover equilíbrio nas relações.", activationText: "Ativo agora Desembaraçador de Relacionamentos, limpando vínculos tóxicos, \ndependência emocional e padrões de dor do passado, presente e futuro em (nome do consulente). Que se estabeleça liberdade afetiva, clareza e harmonia nos relacionamentos. Assim é, está feito, gratidão." },
  "prosperador": { title: "Prosperador", therapistExplanation: "Gráfico que ativa o fluxo da prosperidade, desbloqueia crenças de escassez e alinha o campo com abundância.", clientExplanation: "Será feita uma ativação vibracional para destravar o fluxo financeiro e manifestar abundância material.", activationText: "Ativo agora Prosperador, desbloqueando o fluxo da prosperidade no campo de (nome do consulente), limpando crenças limitantes, medos e escassez do passado, presente e futuro. Que a abundância flua com leveza e constância. Assim é, está feito, gratidão." },
  "antakarana": { title: "Antakarana", therapistExplanation: "Gráfico de conexão espiritual profunda, alinhamento com o Eu Superior e expansão da consciência.", clientExplanation: "Vamos reconectar você com seu Eu Divino e abrir caminhos de expansão espiritual e sabedoria interior.", activationText: "Ativo agora Antakarana, conectando (nome do consulente) com seu Eu Superior, limpando bloqueios espirituais e expandindo sua consciência do passado, presente e futuro. Que a luz da alma se manifeste plenamente. Assim é, está feito, gratidão." },
  "piramide-tao": { title: "Pirâmide Tao", therapistExplanation: "Gráfico que harmoniza o yin e yang, equilibra os aspectos masculino e feminino e traz centramento.", clientExplanation: "Será feita uma harmonização entre forças opostas internas para restaurar paz, equilíbrio e força interior.", activationText: "Ativo agora Pirâmide Tao, equilibrando o yin e yang no campo de (nome do consulente), limpando polaridades desequilibradas do passado, presente e futuro. Que a harmonia e o centramento interno se instalem com fluidez. Assim é, está feito, gratidão." },
  "hexagrama": { title: "Hexagrama", therapistExplanation: "Gráfico de proteção cósmica e alinhamento entre o céu e a terra. Fortalece o campo espiritual e o propósito de vida.", clientExplanation: "Será ativado um campo sagrado que une o divino e o terreno para restaurar sua força espiritual e alinhamento de propósito.", activationText: "Ativo agora Hexagrama, unindo céu e terra no campo de (nome do consulente), limpando bloqueios espirituais e fortalecendo seu propósito divino do passado, presente e \nfuturo. Que a luz e a proteção se estabeleçam. Assim é, está feito, gratidão." },
  "turbilhao-prosperador": { title: "Turbilhão Prosperador", therapistExplanation: "Gráfico de movimento e ativação do campo da abundância. Desbloqueia o fluxo financeiro e traz ação para prosperar.", clientExplanation: "Será ativada uma energia que impulsiona sua vida financeira, removendo bloqueios e ativando sua força de prosperar.", activationText: "Ativo agora Turbilhão Prosperador, movimentando o fluxo da prosperidade no campo de (nome do consulente), limpando estagnações e medos de prosperar do passado, presente e futuro. Que a abundância entre em ação. Assim é, está feito, gratidão." },
  "kit-cromo": { title: "Kit Cromo", therapistExplanation: "Conjunto de gráficos com base na cromoterapia, usados para harmonizar emoções, chakras e vibrações por meio das cores.", clientExplanation: "Será utilizada a vibração das cores para equilibrar seu campo energético e emocional conforme sua necessidade.", activationText: "Ativo agora Kit Cromo, irradiando as frequências de cor necessárias no campo de (nome do consulente), limpando distorções vibracionais e restaurando o equilíbrio emocional e energético do passado, presente e futuro. Assim é, está feito, gratidão." },
  "alta-vitalidade": { title: "Alta Vitalidade", therapistExplanation: "Gráfico que eleva a energia vital, fortalece o sistema imunológico e traz disposição física e mental.", clientExplanation: "Vamos ativar sua energia vital para aumentar a disposição e restaurar sua força interior.", activationText: "Ativo agora Alta Vitalidade, elevando a energia vital de (nome do consulente), limpando padrões de cansaço, fraqueza e desmotivação do passado, presente e futuro. Que a disposição e a força se restabeleçam. Assim é, está feito, gratidão." },
  "cruz-ansata": { title: "Cruz Ansata (Ankh)", therapistExplanation: "Gráfico egípcio que simboliza a vida eterna, renascimento e conexão com o fluxo divino da existência.", clientExplanation: "Será ativada a energia da vida plena, do renascimento e da reconexão com seu poder criador.", activationText: "Ativo agora Cruz Ansata, ativando o fluxo de vida, regeneração e renascimento espiritual em (nome do consulente), limpando padrões de autossabotagem e bloqueios \nvitais do passado, presente e futuro. Que a força da vida eterna se manifeste. Assim é, está feito, gratidão." },
  "vesica-piscis": { title: "Vesica Piscis", therapistExplanation: "Símbolo da criação divina, união dos opostos e expansão do campo criador. Ativa o feminino e masculino sagrados.", clientExplanation: "Vamos ativar a energia criadora divina,equilibrando seus aspectos internos e impulsionando sua manifestação consciente.", activationText: "Ativo agora Vesica Piscis, unificando o sagrado feminino e o sagradomasculino no campo de (nome do consulente), limpando desequilíbrios, repressões e bloqueios criativos do passado, presente e futuro. Que o poder de criação consciente se manifeste plenamente. Assim é, está feito, gratidão." },
};
